### ISSUE TITLE
import error ?

### ISSUE THREAD

**Issue by ucasiggcas** [YannickJadoul/Parselmouth#17]
Dear,
After I `pip install praat-parselmouth`,and then

>>> import parselmouth
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import parselmouth
  File "D:\python\lib\site-packages\parselmouth\__init__.py", line 22, in <module>
    from parselmouth.base import Parselmouth
  File "D:\python\lib\site-packages\parselmouth\base.py", line 30, in <module>
    from parselmouth.adapters.dfp.interface import DFPInterface
  File "D:\python\lib\site-packages\parselmouth\adapters\dfp\interface.py", line 17, in <module>
    from urllib import quote
ImportError: cannot import name 'quote'

Could you help me ?
Thx

**Comment by keggsmurph21** [comment]
Hey @ucasiggcas did you ever resolve this? :)
